### PR TITLE
eccodes -> 2.32.0

### PR DESCRIPTION
**Pull request by EddyCMWF**
Update to the eccodes version.

It includes (amongst otherb things) this change required for Glofas grids:
https://jira.ecmwf.int/browse/ECC-1671

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf/ecmwflibs?pullRequest=19) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/ecmwflibs?pullRequest=19) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/ecmwflibs?pullRequest=19) it.</sub>

**Comment by shahramn** [comment]
ecCodes v2.32.0 is still under development. Most likely to be released in Sep/Oct timeframe

**Comment by EddyCMWF** [comment]
> ecCodes v2.32.0 is still under development. Most likely to be released in Sep/Oct time frame

Hi @shahramn , yes I spotted that when the actions failed so deleted the PR. I then also discovered the other 2 PRs in waiting.

**Comment by EddyCMWF** [comment]
Hi Iain,
I've just merged the changes from master, any chance you could give it a review once it passes the tests it can pass.

(I also removed the .vscode directory which contains users personal vsconfig options which I think should not have been added in the first place. I'm happy to add it back in if it is there for a reason.)

Eddy

**Comment by shahramn** [comment]
Many thanks

**Pull request merged**
